#!/bin/bash
# Spawn a wave of tmux subagents. Each subagent runs pi with the task prompt
# base64-encoded to avoid shell quoting issues (the ONLY reliable method).
#
# Usage: bash spawn-wave.sh T001 T003
#
# Prerequisites: tasks/TASK-XXXX-prompt must exist (generated by generate-prompts.py)
# Output: tasks/TASK-XXXX.out (subagent stdout/stderr), tasks/TASK-XXXX.done (marker)

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TMUX_SESSION_PREFIX="${TMUX_SESSION_PREFIX:-task}"

for tid in "$@"; do
  PROMPT_FILE="$PROJECT_DIR/tasks/${tid}-prompt"

  # ── Pre-flight checks ────────────────────────────────────────────
  if [ -f "$PROJECT_DIR/tasks/${tid}.done" ]; then
    echo "SKIP ${tid}: already done"
    continue
  fi

  if [ ! -f "$PROMPT_FILE" ]; then
    echo "SKIP ${tid}: no prompt file at ${PROMPT_FILE}"
    continue
  fi

  # ── Generate runner script via Python ─────────────────────────────
  # Base64-encode the prompt so it's safe in any shell context.
  # This avoids ALL quoting issues: no heredocs, no send-keys, no escaping.
  python3 -c "
import base64, os

tid = '${tid}'
project_dir = '${PROJECT_DIR}'
prompt_file = os.path.join(project_dir, 'tasks', f'{tid}-prompt')
script = f'/tmp/task-{tid}.sh'

with open(prompt_file) as f:
    prompt_b64 = base64.b64encode(f.read().encode()).decode()

with open(script, 'w') as f:
    f.write('#!/bin/bash\n')
    f.write(f'cd {project_dir}\n')
    f.write(f'PROMPT_B64=\"{prompt_b64}\"\n')
    f.write(f'pi --thinking low -p \"\$(echo \"\$PROMPT_B64\" | base64 -d)\" 2>&1 | tee tasks/{tid}.out\n')
    f.write(f'echo \"{tid}_DONE\" > tasks/{tid}.done\n')

os.chmod(script, 0o755)
print(f'Generated /tmp/task-{tid}.sh ({len(prompt_b64)} bytes b64)')
"

  # ── Kill stale session ───────────────────────────────────────────
  tmux kill-session -t "${TMUX_SESSION_PREFIX}-${tid}" 2>/dev/null || true

  # ── Launch ───────────────────────────────────────────────────────
  tmux new-session -d -s "${TMUX_SESSION_PREFIX}-${tid}" "bash /tmp/task-${tid}.sh"
  echo "SPAWN ${tid}"
done

echo "---"
echo "Active: $(tmux ls 2>/dev/null | grep "${TMUX_SESSION_PREFIX}-" | wc -l | tr -d ' ') sessions"
tmux ls 2>/dev/null | grep "${TMUX_SESSION_PREFIX}-" || echo "(none)"
